AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  AMI:
    Type: String
    Default: ami-0d5eff06f840b45e9
  Key:
    Type: String
    Default: ledivan.pem
  PublicSubnet1:
    Type: String
    Default: subnet-02fe73f7ff599fcb5
  PublicSecurityGroup:
    Type: String
    Default: sg-07f3f6dbd1bb7d585
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref Key
      Tags:
        - Key: Name
          Value: Simple Server
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: PublicSecurityGroup
          SubnetId:
            Ref: PublicSubnet1
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum -y update
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo echo '<h1>Hello from ${AWS::Region}</h1>' > /var/www/html/index.html